# Generated by Django 5.1.3 on 2024-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_review_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.SmallIntegerField(),
        ),
    ]
