# Generated by Django 5.1.3 on 2024-11-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='title_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
