# Generated by Django 5.1.3 on 2024-11-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_title_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='title_id',
        ),
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(default='hh2'),
            preserve_default=False,
        ),
    ]
