# Generated by Django 5.1.3 on 2024-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
